[project]
name = "ns2"
version = "2.0.41"
description = "ns2 is collection of tools to support Novus Power Products"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "dbus-next>=0.2.3",
    "nicegui>=3.8.0",
    "systemd-python",
    "pyinstaller>=6.19.0",
    "setuptools>=82.0.0",
    "sysv-ipc>=1.2.0",
]


[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"

[project.scripts]
ns-admin = "ns2.ui.main:main"

[tool.ruff.lint]
ignore = ["F541"]  # Skips line-length and missing docstring errors
