#!/bin/bash
set -e

#exec &> /etc/ns/postinstall.log

case "$1" in
    configure)


        
        # making ns-admin and ns-user groups
        getent group nsadmin >/dev/null 2>&1 || groupadd nsadmin
        getent group nsuser  >/dev/null 2>&1 || groupadd nsuser

        # allow root user to flow through polkit stuff
        usermod -aG nsadmin root
        usermod -aG nsuser root

        firewall-cmd --permanent --zone=public --add-service=ssh 2>/dev/null || true
        firewall-cmd --permanent --zone=public --add-service=snmptrap 2>/dev/null || true
        firewall-cmd --permanent --zone=public --add-service=https 2>/dev/null || true
        firewall-cmd --permanent --zone=public --add-service=snmp 2>/dev/null || true

        # Reload to apply changes
        firewall-cmd --reload 2>/dev/null || true

        echo "Added rules and reloaded firewalld"

        mkdir -p /etc/nginx/ssl

        echo "Made self-signed directory"

        if [ ! -f /etc/nginx/ssl/selfsigned.key ] || [ ! -f /etc/nginx/ssl/selfsigned.crt ]; then
   		 LD_LIBRARY_PATH=/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu \
    		openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        	-keyout /etc/nginx/ssl/selfsigned.key \
        	-out /etc/nginx/ssl/selfsigned.crt \
        	-subj "/C=US/ST=Missouri/L=Independence/O=ns2/CN=var"
	    fi

        echo "Generated self-signed cert"

        rm -f /etc/nginx/sites-enabled/default
        ln -sf /etc/nginx/sites-available/ns2-ui.conf /etc/nginx/sites-enabled/

        echo "Copied over reverse proxy config"

        systemctl reload nginx 2>/dev/null || true

        echo "Reloaded nginx"

        ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
esac

#DEBHELPER#

exit 0
